name: hackathon_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  permission_handler: ^10.2.0
  elementary: ^2.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  dio: ^5.0.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.1.1
  auto_route: ^5.0.4
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  logger: ^1.1.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  retrofit_generator: ^5.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true

  assets:
    - assets/
